name: hollow-ri-model
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - geopandas
  - rasterio
  - gdal
  - rasterstats
  - landlab
  - openpyxl
